name: wisp_spm
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2022.10.11
  - certifi=2022.12.7
  - decorator=5.1.1
  - intel-openmp=2022.1.0
  - libcxx=14.0.6
  - libedit=3.1.20221030
  - libffi=3.4.2
  - libgfortran=3.0.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - ncurses=6.3
  - networkx=2.2
  - numpy=1.17.4
  - numpy-base=1.17.4
  - openssl=1.1.1s
  - pip=22.3.1
  - python=3.7.15
  - readline=8.2
  - scipy=1.3.1
  - setuptools=65.5.0
  - six=1.16.0
  - sqlite=3.40.0
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.8
  - zlib=1.2.13

